name=input("what is your name? ")
print("nice to meet you " + name + "!")
age = input("your age ? ")
print("so , you are " + str(age) + " years old " + name + "!")
colour=input("what is your  favourite colour? ")
print("So, your favourite colour is "  +colour + "!")
